# Author: Mikita Sazanovich

STATE_PROJECT = [0, 1, 2, 11, 12, 19, 20]
STATE_DIM = len(STATE_PROJECT)

MOVES_TOTAL = 5
ATTACK_CREEP = MOVES_TOTAL
ATTACK_HERO = MOVES_TOTAL + 1
ATTACK_TOWER = MOVES_TOTAL + 2
